import pandas as pd
df = pd.read_csv("data/student_performance.csv")
print("2. First 5 rows of the dataset:")
print(df.head().to_string())
print("\n")
print("3. No. of rows and columns in the dataset(Rows, Columns):", df.shape)
print("\n")
print("4. Column names in the dataset:", df.columns.tolist())
print("\n")
print("5. Checking whether the dataset contains missing values.")
print(df.isnull().sum())
print("\n")
print("6. Average Final_Score:", df['Final_Score'].mean())
print("\n")
print("7. Student with highest Final_Score:", df.Student[df['Final_Score'].idxmax()])
print("\n")
df['Improvement'] = df['Final_Score'] - df['Previous_Score']
print("\n")
print("9. Students with high attendance:", df[df['Attendance'] > 80]['Student'].tolist())
df_sorted = df.sort_values(by='Final_Score', ascending=False)
df_sorted.to_csv('data/processed_student_performance.csv', index=False)